before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
env:
  global:
  - AWS_DEFAULT_REGION=eu-west-1
  - AWS_REGION=eu-west-1
  - AWS_SECRET_ACCESS_KEY=fake_secret
  - AWS_ACCESS_KEY_ID=fake_id
script:
- env | grep AWS >> ./env.txt && cat ./env.txt
- aws configure list
